#!/usr/bin/env bash
# Configures an Nginx server for redirections
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo sed -i '/# pass PHP/i \\tlocation /redirect_me {\n\t\treturn 301 https://twitter.com/beingnile;\n\t}\n' /etc/nginx/sites-available/default
sudo service nginx restart
