#!/usr/bin/env bash
# Configures an ubuntu with nginx
FILE='/etc/nginx/sites-available/default'

apt-get update && apt-get upgrade -y
apt-get install nginx -y
echo "Ceci n'est pas une page\n" > /var/www/html/my_404.html
chown -R $USER:$USER /var/www/
sed -i "/server_name _;/a \\\n        error_page 404 \/my_404.html;\n        location = \/my_404.html {\n            internal;\n        }" $FILE
service nginx restart
