#!/usr/bin/env bash
# Configures a new ubuntu server into a load balancer with haproxy
apt-get update && apt-get upgrade -y
apt-get install haproxy -y
sed -i '$a\
frontend my_frontend\
\ \ \ \ \ \ \ \ bind *:80\
\ \ \ \ \ \ \ \ mode http\
\ \ \ \ \ \ \ \ default_backend my_backend' /etc/haproxy/haproxy.cfg
sed -i '$a\
backend my_backend\
\ \ \ \ \ \ \ \ mode http\
\ \ \ \ \ \ \ \ balance roundrobin\
\ \ \ \ \ \ \ \ server web-01 54.158.218.156:80 check\
\ \ \ \ \ \ \ \ server web-02 100.26.49.0:80 check' /etc/haproxy/haproxy.cfg
service haproxy restart
