#!/usr/bin/env bash
# Install and configure HAProxy
sudo apt install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt install haproxy=2.4.\* -y
sudo apt update && sudo apt upgrade -y
