#!/usr/bin/env bash
# Configures a new ubuntu server into a load balancer with haproxy
apt-get update && apt-get upgrade -y
apt-get install haproxy
sed -i '$a\
frontend my_frontend\
\ \ \ \ \ \ \ \ bind *:80\
\ \ \ \ \ \ \ \ mode http\
\ \ \ \ \ \ \ \ default_backend my_backend' /etc/haproxy/haproxy.cfg
sed -i '$a\
backend my_backend\
\ \ \ \ \ \ \ \ mode http\
\ \ \ \ \ \ \ \ balance roundrobin\
\ \ \ \ \ \ \ \ server web-01 100.26.226.159:80 check\
\ \ \ \ \ \ \ \ server web-02 54.227.128.21:80 check' /etc/haproxy/haproxy.cfg
service haproxy restart
