#!/usr/bin/env bash
# Configures a server with nginx
apt-get update && apt-get upgrade -y
apt-get install nginx -y
sed -i 's/listen \[::\]:80 default_server;/    # listen [::]:80 default_server;/' /etc/nginx/sites-enabled/default
service nginx start
