#!/usr/bin/env bash
# Displays numbers from 1 to 100, FizzBuzz when the number
# is a multiple of 3 and 5, Fizz when a multiple of 3 and 
# Buzz when a multiple of 5.

i=1
while ((i <= 100))
do
	echo "$i"
	((i++))
done
