#!/usr/bin/env bash
# Configures /etc/hosts file
cp /etc/hosts ~/hosts.new
sed -i 's/^127.0.0.1.*localhost$/127.0.0.2 localhost/' ~/hosts.new
echo '8.8.8.8 facebook.com' | sudo tee -a ~/hosts.new >/dev/null
cp -f ~/hosts.new /etc/hosts
